"""add video task persistence

Revision ID: 04674948678b
Revises: 84af435ce6f4
Create Date: 2026-05-27 23:28:17.502561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '04674948678b'
down_revision: Union[str, None] = '84af435ce6f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the persisted video task table."""

    bind = op.get_bind()
    protocol_type = (
        postgresql.ENUM(
            'openai',
            'anthropic',
            'both',
            name='protocol_type_enum',
            create_type=False,
        )
        if bind.dialect.name == 'postgresql'
        else sa.Enum('openai', 'anthropic', 'both', name='protocol_type_enum')
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openaiapi_video_tasks',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('video_id', sa.VARCHAR(length=191), nullable=True),
    sa.Column('request_log_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('node_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('ownerapp_id', sa.Text(), nullable=True),
    sa.Column('api_key_id', sa.Text(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('dispatching', 'processing', 'succeeded', 'failed', 'canceled', name='videotaskstatus'), nullable=False),
    sa.Column('node_url', sa.Text(), nullable=False),
    sa.Column('backend_api_key', sa.Text(), nullable=True),
    sa.Column('protocol_type', protocol_type, nullable=False),
    sa.Column('request_proxy_url', sa.Text(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('create_response_payload', sa.JSON(), nullable=True),
    sa.Column('latest_response_payload', sa.JSON(), nullable=True),
    sa.Column('latest_response_text', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('recovery_attempts', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('content_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('content_size', sa.Integer(), nullable=True),
    sa.Column('content_data', sa.LargeBinary(), nullable=True),
    sa.Column('last_recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['openaiapi_nodes.id'], name='openaiapi_video_tasks_node_fkey'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', name='uix_openaiapi_video_tasks_video_id')
    )
    with op.batch_alter_table('openaiapi_video_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_openaiapi_video_tasks_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_video_tasks_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_video_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_video_tasks_last_recovered_at'), ['last_recovered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_video_tasks_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_video_tasks_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_video_tasks_ownerapp_id'), ['ownerapp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_video_tasks_protocol_type'), ['protocol_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_video_tasks_request_log_id'), ['request_log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_video_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_video_tasks_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_video_tasks_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the persisted video task table."""

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openaiapi_video_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openaiapi_video_tasks_video_id'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_video_tasks_updated_at'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_video_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_video_tasks_request_log_id'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_video_tasks_protocol_type'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_video_tasks_ownerapp_id'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_video_tasks_node_id'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_video_tasks_model_name'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_video_tasks_last_recovered_at'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_video_tasks_created_at'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_video_tasks_completed_at'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_video_tasks_api_key_id'))

    op.drop_table('openaiapi_video_tasks')
    # ### end Alembic commands ###
