"""add northbound apikey and app quotas

Revision ID: 0e4bdcd25316
Revises: bafe420807ac
Create Date: 2026-04-17 12:57:12.752987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '0e4bdcd25316'
down_revision: Union[str, None] = 'bafe420807ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openaiapi_app_quotas',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('ownerapp_id', sa.Text(), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=True),
    sa.Column('call_limit', sa.BigInteger(), nullable=True),
    sa.Column('call_used', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_tokens_limit', sa.BigInteger(), nullable=True),
    sa.Column('total_tokens_used', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('last_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ownerapp_id', 'order_id', name='uix_openaiapi_app_quota_app_order')
    )
    with op.batch_alter_table('openaiapi_app_quotas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_openaiapi_app_quotas_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_app_quotas_ownerapp_id'), ['ownerapp_id'], unique=False)

    op.create_table('openaiapi_apikey_quotas',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('api_key_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=True),
    sa.Column('call_limit', sa.BigInteger(), nullable=True),
    sa.Column('call_used', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_tokens_limit', sa.BigInteger(), nullable=True),
    sa.Column('total_tokens_used', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('last_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['openaiapi_apikeys.id'], name='openaiapi_apikey_quota_key_fkey'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'order_id', name='uix_openaiapi_apikey_quota_key_order')
    )
    with op.batch_alter_table('openaiapi_apikey_quotas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_openaiapi_apikey_quotas_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_apikey_quotas_order_id'), ['order_id'], unique=False)

    op.create_table('openaiapi_apikey_quota_usage',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('quota_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('api_key_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('proxy_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('nodelog_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('ownerapp_id', sa.Text(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('request_action', sa.Text(), nullable=True),
    sa.Column('call_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['openaiapi_apikeys.id'], name='openaiapi_apikey_quota_usage_key_fkey'),
    sa.ForeignKeyConstraint(['nodelog_id'], ['openaiapi_nodelogs.id'], name='openaiapi_apikey_quota_usage_log_fkey'),
    sa.ForeignKeyConstraint(['proxy_id'], ['openaiapi_proxy.id'], name='openaiapi_apikey_quota_usage_proxy_fkey'),
    sa.ForeignKeyConstraint(['quota_id'], ['openaiapi_apikey_quotas.id'], name='openaiapi_apikey_quota_usage_quota_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('openaiapi_apikey_quota_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_openaiapi_apikey_quota_usage_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_apikey_quota_usage_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_apikey_quota_usage_nodelog_id'), ['nodelog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_apikey_quota_usage_ownerapp_id'), ['ownerapp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_apikey_quota_usage_proxy_id'), ['proxy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_apikey_quota_usage_quota_id'), ['quota_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_apikey_quota_usage_request_action'), ['request_action'], unique=False)

    op.create_table('openaiapi_app_quota_usage',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('quota_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('ownerapp_id', sa.Text(), nullable=False),
    sa.Column('api_key_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('proxy_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('nodelog_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('request_action', sa.Text(), nullable=True),
    sa.Column('call_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nodelog_id'], ['openaiapi_nodelogs.id'], name='openaiapi_app_quota_usage_log_fkey'),
    sa.ForeignKeyConstraint(['proxy_id'], ['openaiapi_proxy.id'], name='openaiapi_app_quota_usage_proxy_fkey'),
    sa.ForeignKeyConstraint(['quota_id'], ['openaiapi_app_quotas.id'], name='openaiapi_app_quota_usage_quota_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('openaiapi_app_quota_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_openaiapi_app_quota_usage_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_app_quota_usage_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_app_quota_usage_nodelog_id'), ['nodelog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_app_quota_usage_ownerapp_id'), ['ownerapp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_app_quota_usage_proxy_id'), ['proxy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_app_quota_usage_quota_id'), ['quota_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_app_quota_usage_request_action'), ['request_action'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openaiapi_app_quota_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openaiapi_app_quota_usage_request_action'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_app_quota_usage_quota_id'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_app_quota_usage_proxy_id'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_app_quota_usage_ownerapp_id'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_app_quota_usage_nodelog_id'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_app_quota_usage_model_name'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_app_quota_usage_api_key_id'))

    op.drop_table('openaiapi_app_quota_usage')
    with op.batch_alter_table('openaiapi_apikey_quota_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openaiapi_apikey_quota_usage_request_action'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_apikey_quota_usage_quota_id'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_apikey_quota_usage_proxy_id'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_apikey_quota_usage_ownerapp_id'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_apikey_quota_usage_nodelog_id'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_apikey_quota_usage_model_name'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_apikey_quota_usage_api_key_id'))

    op.drop_table('openaiapi_apikey_quota_usage')
    with op.batch_alter_table('openaiapi_apikey_quotas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openaiapi_apikey_quotas_order_id'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_apikey_quotas_api_key_id'))

    op.drop_table('openaiapi_apikey_quotas')
    with op.batch_alter_table('openaiapi_app_quotas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openaiapi_app_quotas_ownerapp_id'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_app_quotas_order_id'))

    op.drop_table('openaiapi_app_quotas')
    # ### end Alembic commands ###
