""""node_apikey_quota_freeze_reset_cycle"

Revision ID: 3c054a7ffdb8
Revises: df9c5f6f4c79
Create Date: 2026-09-08 15:38:20.172698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '3c054a7ffdb8'
down_revision: Union[str, None] = 'df9c5f6f4c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# PostgreSQL 枚举类型需显式创建，autogenerate 不会生成该 DDL
quota_reset_cycle_enum = sa.Enum('none', 'daily', 'weekly', 'monthly', name='quotaresetcycle')


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    quota_reset_cycle_enum.create(conn, checkfirst=True)

    with op.batch_alter_table('openaiapi_node_apikeys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quota_reset_cycle', quota_reset_cycle_enum, server_default='none', nullable=False))
        batch_op.add_column(sa.Column('quota_next_reset_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('frozen_until', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('freeze_reason', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_openaiapi_node_apikeys_frozen_until'), ['frozen_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_node_apikeys_quota_next_reset_at'), ['quota_next_reset_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_node_apikeys_quota_reset_cycle'), ['quota_reset_cycle'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openaiapi_node_apikeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openaiapi_node_apikeys_quota_reset_cycle'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_node_apikeys_quota_next_reset_at'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_node_apikeys_frozen_until'))
        batch_op.drop_column('freeze_reason')
        batch_op.drop_column('frozen_at')
        batch_op.drop_column('frozen_until')
        batch_op.drop_column('quota_next_reset_at')
        batch_op.drop_column('quota_reset_cycle')

    quota_reset_cycle_enum.drop(conn, checkfirst=True)
    # ### end Alembic commands ###
