"""add_image_generation_adapter

Revision ID: 41f494c15284
Revises: cb04f8f0f5a2
Create Date: 2026-08-20 15:34:47.758674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '41f494c15284'
down_revision: Union[str, None] = 'cb04f8f0f5a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openaiapi_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_provider', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openaiapi_nodes', schema=None) as batch_op:
        batch_op.drop_column('image_provider')

    # ### end Alembic commands ###
