"""

Revision ID: 817dfe2df2ef
Revises: af7f2705e7ff
Create Date: 2026-03-06 11:32:42.642370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '817dfe2df2ef'
down_revision: Union[str, None] = 'af7f2705e7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openaiapi_nodelogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_ip', sa.VARCHAR(), nullable=True))
        batch_op.create_index(batch_op.f('ix_openaiapi_nodelogs_client_ip'), ['client_ip'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openaiapi_nodelogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openaiapi_nodelogs_client_ip'))
        batch_op.drop_column('client_ip')

    # ### end Alembic commands ###
