"""

Revision ID: af7f2705e7ff
Revises: d50f6d625d70
Create Date: 2026-01-10 13:59:32.169233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = 'af7f2705e7ff'
down_revision: Union[str, None] = 'd50f6d625d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openaiapi_nodelogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_openaiapi_nodelogs_first_response_at'), ['first_response_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openaiapi_nodelogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openaiapi_nodelogs_first_response_at'))
        batch_op.drop_column('first_response_at')

    # ### end Alembic commands ###
