"""daily and weekly usage rollup

Revision ID: bafe420807ac
Revises: c2a5c7e5f3b1
Create Date: 2026-04-16 17:32:25.022990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = 'bafe420807ac'
down_revision: Union[str, None] = 'c2a5c7e5f3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openaiapi_app_daily_usage',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('ownerapp_id', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('day_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('call_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('request_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('response_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ownerapp_id', 'model_name', 'day_start', name='uix_openaiapi_app_daily_usage_unique')
    )
    with op.batch_alter_table('openaiapi_app_daily_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_openaiapi_app_daily_usage_day_start'), ['day_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_app_daily_usage_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_app_daily_usage_ownerapp_id'), ['ownerapp_id'], unique=False)

    op.create_table('openaiapi_app_weekly_usage',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('ownerapp_id', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('week_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('call_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('request_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('response_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ownerapp_id', 'model_name', 'week_start', name='uix_openaiapi_app_weekly_usage_unique')
    )
    with op.batch_alter_table('openaiapi_app_weekly_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_openaiapi_app_weekly_usage_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_app_weekly_usage_ownerapp_id'), ['ownerapp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_app_weekly_usage_week_start'), ['week_start'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openaiapi_app_weekly_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openaiapi_app_weekly_usage_week_start'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_app_weekly_usage_ownerapp_id'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_app_weekly_usage_model_name'))

    op.drop_table('openaiapi_app_weekly_usage')
    with op.batch_alter_table('openaiapi_app_daily_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openaiapi_app_daily_usage_ownerapp_id'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_app_daily_usage_model_name'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_app_daily_usage_day_start'))

    op.drop_table('openaiapi_app_daily_usage')
    # ### end Alembic commands ###
