"""
Add cached_tokens column to usage tables.

为请求日志表和用量聚合表增加 cached_tokens 列，
独立存储缓存命中令牌数，保证 total_tokens = request_tokens + response_tokens 恒等。

Revision ID: cb04f8f0f5a2
Revises: 9f4f5c2b1d7a
Create Date: 2026-07-06 14:29:15.575706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = 'cb04f8f0f5a2'
down_revision: Union[str, None] = '9f4f5c2b1d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openaiapi_app_daily_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cached_tokens', sa.BigInteger(), server_default='0', nullable=False))

    with op.batch_alter_table('openaiapi_app_monthly_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cached_tokens', sa.BigInteger(), server_default='0', nullable=False))

    with op.batch_alter_table('openaiapi_app_weekly_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cached_tokens', sa.BigInteger(), server_default='0', nullable=False))

    with op.batch_alter_table('openaiapi_nodelogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cached_tokens', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openaiapi_nodelogs', schema=None) as batch_op:
        batch_op.drop_column('cached_tokens')

    with op.batch_alter_table('openaiapi_app_weekly_usage', schema=None) as batch_op:
        batch_op.drop_column('cached_tokens')

    with op.batch_alter_table('openaiapi_app_monthly_usage', schema=None) as batch_op:
        batch_op.drop_column('cached_tokens')

    with op.batch_alter_table('openaiapi_app_daily_usage', schema=None) as batch_op:
        batch_op.drop_column('cached_tokens')

    # ### end Alembic commands ###
