"""

Revision ID: d50f6d625d70
Revises: 289442e9b00c
Create Date: 2025-12-02 11:48:41.432151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision: str = 'd50f6d625d70'
down_revision: Union[str, None] = '289442e9b00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openaiapi_nodelogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_openaiapi_nodelogs_end_at'), ['end_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_nodelogs_latency'), ['latency'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_nodelogs_start_at'), ['start_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openaiapi_nodelogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openaiapi_nodelogs_start_at'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_nodelogs_latency'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_nodelogs_end_at'))

    # ### end Alembic commands ###
