""""节点独立APIKEY记录与优先级权重"

Revision ID: df9c5f6f4c79
Revises: cb04f8f0f5a2
Create Date: 2026-09-07 16:15:37.199093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = 'df9c5f6f4c79'
down_revision: Union[str, None] = 'cb04f8f0f5a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openaiapi_node_apikeys',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('node_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='1', nullable=False),
    sa.Column('max_tokens', sa.BigInteger(), nullable=True),
    sa.Column('tokens_used', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disable_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['openaiapi_nodes.id'], name='openaiapi_node_apikeys_node_fkey'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'api_key_hash', name='uix_openaiapi_node_apikeys_node_hash')
    )
    with op.batch_alter_table('openaiapi_node_apikeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_openaiapi_node_apikeys_api_key_hash'), ['api_key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_node_apikeys_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_openaiapi_node_apikeys_node_id'), ['node_id'], unique=False)

    with op.batch_alter_table('openaiapi_nodelogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('node_api_key_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_openaiapi_nodelogs_node_api_key_id'), ['node_api_key_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openaiapi_nodelogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openaiapi_nodelogs_node_api_key_id'))
        batch_op.drop_column('node_api_key_id')

    with op.batch_alter_table('openaiapi_node_apikeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openaiapi_node_apikeys_node_id'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_node_apikeys_enabled'))
        batch_op.drop_index(batch_op.f('ix_openaiapi_node_apikeys_api_key_hash'))

    op.drop_table('openaiapi_node_apikeys')
    # ### end Alembic commands ###
