"""add node reason column

Revision ID: e30ff8554e54
Revises: 4a8d0d5dbf12
Create Date: 2026-06-05 15:22:42.285916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30ff8554e54'
down_revision: Union[str, None] = '4a8d0d5dbf12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openaiapi_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openaiapi_nodes', schema=None) as batch_op:
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
