
from datetime import datetime
from typing import Annotated, Any, List

from fastapi import APIRouter, Depends, Request
from openaiproxy.api.utils import check_api_key
from openaiproxy.services.nodemanager.schemas import Node
from openaiproxy.logging import logger

router = APIRouter(tags=["节点管理"])

@router.get('/nodes/status', dependencies=[Depends(check_api_key)])
def node_status(node_manager: Any):
    """Show nodes status."""
    try:
        return node_manager.status
    except:  # noqa
        return False

@router.get('/health')
def node_status(node_manager: Any):
    """Show nodes status."""
    try:
       return bool(node_manager.status)
    except:  # noqa
        return False

@router.post('/nodes/add', dependencies=[Depends(check_api_key)])
def add_node(node: Node, raw_request: Request = None, node_manager: Any = None):
    """Add a node to the manager.

    - url (str): A http url. Can be the url generated by
        `lmdeploy serve api_server`.
    - status (Dict): The description of the node. An example:
        {models: ['internlm-chat-7b],  speed: 1}. The speed here can be
        RPM or other metric. All the values of nodes should be the same metric.
    """
    try:
        res = node_manager.add(node.url, node.status)
        if res is not None:
            logger.error(f'add node {node.url} failed, {res}')
            return res
        logger.info(f'add node {node.url} successfully')
        return 'Added successfully'
    except:  # noqa
        return 'Failed to add, please check the input url.'


@router.post('/nodes/remove', dependencies=[Depends(check_api_key)])
def remove_node(node_url: str, node_manager: Any = None):
    """Show available models."""
    try:
        node_manager.remove(node_url)
        logger.info(f'delete node {node_url} successfully')
        return 'Deleted successfully'
    except:  # noqa
        logger.error(f'delete node {node_url} failed.')
        return 'Failed to delete, please check the input url.'

